language: haskell

ghc:
  - 7.6
  - 7.8

before_install:
  - cabal install codecov-haskell-0.4.0.2

script:
  - cabal configure --enable-tests --enable-library-coverage -v2
  - cabal build
  - run-cabal-test --cabal-name=cabal --show-details=always

after_script:
  - codecov-haskell test-one --exclude-dir=test1 --dont-send --display-report
  - codecov-haskell test-two --exclude-dir=test2 --dont-send --display-report
  - codecov-haskell test-three --exclude-dir=test3 --dont-send --display-report
  - codecov-haskell test-one test-two test-three --exclude-dir=test1 --exclude-dir=test2 --exclude-dir=test3 --dont-send --display-report
