language: haskell

ghc:
  - 7.6
  - 7.8

before_install:
  - git clone https://github.com/guillaume-nargeot/codecov-haskell
  - cd codecov-haskell
  - git checkout 34661200380500a2c0175f208739efac870af791
  - cabal install
  - cd ..

script:
  - cabal configure --enable-tests --enable-library-coverage -v2
  - cabal build
  - run-cabal-test --cabal-name=cabal --show-details=always

after_script:
  - codecov-haskell test-one --exclude-dir=test1 --dont-send --display-report
  - codecov-haskell test-two --exclude-dir=test2 --dont-send --display-report
  - codecov-haskell test-three --exclude-dir=test3 --dont-send --display-report
  - codecov-haskell test-one test-two test-three --exclude-dir=test1 --exclude-dir=test2 --exclude-dir=test3 --dont-send --display-report
