language: haskell

ghc:
#  - 7.6
  - 7.8

before_install:
  - git clone -b develop https://github.com/guillaume-nargeot/codecov-haskell
#  - cd codecov-haskell
#  - cabal install
#  - cd ..

script:
  - cabal configure --enable-tests --enable-library-coverage -v2
#  - cabal build
#  - run-cabal-test --cabal-name=cabal --show-details=always

after_script:
  #- codecov-haskell test-one test-two --exclude-dir=test1 --exclude-dir=test2 --dont-send --display-report
  - curl -X POST -H 'Content-Type: application/json' -d '{ \"coverage\": { \"src/Util.hs\": [null, null, null, 0, true, 1] } }' https://codecov.io/upload/v1?token=dbd3e4a7-86e2-4537-b607-142bf46d7766&commit=$TRAVIS_COMMIT&branch=develop&travis_job_id=$TRAVIS_JOB_ID
